##################################################################################################
#
##################################################################################################

##################################################################################################
#
##################################################################################################

##################################################################################################
#
##################################################################################################

##################################################################################################
#
##################################################################################################
# apiVersion: v1
# kind: Service
# metadata:
#   name: appguard-book-page
#   labels:
#     app: appguard-book-page
# spec:
#   ports:
#   - port: 30010
#     name: http
#   selector:
#     app: appguard-book-page
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: appguard-book-page
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: appguard-book-page
#         version: v1
#     spec:
#       containers:
#       - name: appguard-book-page
#         image: appguard/book_page:v0.1
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 30010
# ---


# apiVersion: v1
# kind: Service
# metadata:
#   name: productpage
#   labels:
#     app: productpage
# spec:
#   ports:
#   - port: 9080
#     name: http
#   selector:
#     app: productpage
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: productpage-v1
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: productpage
#         version: v1
#     spec:
#       containers:
#       - name: productpage
#         image: istio/examples-bookinfo-productpage-v1:0.2.8
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 9080
# ---
###########################################################################
# Ingress resource (gateway)
##########################################################################
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: gateway
#   annotations:
#     kubernetes.io/ingress.class: "istio"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /productpage
#         backend:
#           serviceName: productpage
#           servicePort: 9080
#       - path: /login
#         backend:
#           serviceName: productpage
#           servicePort: 9080
#       - path: /logout
#         backend:
#           serviceName: productpage
#           servicePort: 9080
#       - path: /api/v1/products.*
#         backend:
#           serviceName: productpage
#           servicePort: 9080
# ---
