apiVersion: v1
kind: Service
metadata:
  name: appguard-user-reviews-v2
  labels:
    app: appguard-user-reviews-v2
spec:
  ports:
  - port: 30002
    name: http
  selector:
    app: appguard-user-reviews-v2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appguard-user-reviews-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appguard-user-reviews-v2
        version: v1
    spec:
      containers:
      - name: appguard-user-reviews-v2
        image: appguard/user_reviews_v2:v0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 30002
---
